// <auto-generated />
namespace SinglePageCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class additemsToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(additemsToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201505071317151_add-itemsToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
