// <auto-generated />
namespace SinglePageCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updateimagecat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateimagecat));
        
        string IMigrationMetadata.Id
        {
            get { return "201506202339086_update-image-cat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
