// <auto-generated />
namespace SinglePageCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updatecontentaddcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecontentaddcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201505131224503_update-content-add-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
