// <auto-generated />
namespace SinglePageCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updateinsight0092 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateinsight0092));
        
        string IMigrationMetadata.Id
        {
            get { return "201504272051213_update-insight0092"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
