// <auto-generated />
namespace SinglePageCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class configcontentcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configcontentcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201505280720087_config-content-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
